/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface AccountAbstractionWalletInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "entryPoint"
      | "executeUserOperation"
      | "owner"
      | "setEntryPoint"
      | "transferERC20"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "UserOperationExecuted" | "WalletCreated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "entryPoint",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "executeUserOperation",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setEntryPoint",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferERC20",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "entryPoint", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "executeUserOperation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setEntryPoint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferERC20",
    data: BytesLike
  ): Result;
}

export namespace UserOperationExecutedEvent {
  export type InputTuple = [sender: AddressLike, userOp: BytesLike];
  export type OutputTuple = [sender: string, userOp: string];
  export interface OutputObject {
    sender: string;
    userOp: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WalletCreatedEvent {
  export type InputTuple = [user: AddressLike];
  export type OutputTuple = [user: string];
  export interface OutputObject {
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AccountAbstractionWallet extends BaseContract {
  connect(runner?: ContractRunner | null): AccountAbstractionWallet;
  waitForDeployment(): Promise<this>;

  interface: AccountAbstractionWalletInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  entryPoint: TypedContractMethod<[], [string], "view">;

  executeUserOperation: TypedContractMethod<
    [userOp: BytesLike],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  setEntryPoint: TypedContractMethod<
    [_entryPoint: AddressLike],
    [void],
    "nonpayable"
  >;

  transferERC20: TypedContractMethod<
    [token: AddressLike, to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "entryPoint"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "executeUserOperation"
  ): TypedContractMethod<[userOp: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setEntryPoint"
  ): TypedContractMethod<[_entryPoint: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferERC20"
  ): TypedContractMethod<
    [token: AddressLike, to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "UserOperationExecuted"
  ): TypedContractEvent<
    UserOperationExecutedEvent.InputTuple,
    UserOperationExecutedEvent.OutputTuple,
    UserOperationExecutedEvent.OutputObject
  >;
  getEvent(
    key: "WalletCreated"
  ): TypedContractEvent<
    WalletCreatedEvent.InputTuple,
    WalletCreatedEvent.OutputTuple,
    WalletCreatedEvent.OutputObject
  >;

  filters: {
    "UserOperationExecuted(address,bytes)": TypedContractEvent<
      UserOperationExecutedEvent.InputTuple,
      UserOperationExecutedEvent.OutputTuple,
      UserOperationExecutedEvent.OutputObject
    >;
    UserOperationExecuted: TypedContractEvent<
      UserOperationExecutedEvent.InputTuple,
      UserOperationExecutedEvent.OutputTuple,
      UserOperationExecutedEvent.OutputObject
    >;

    "WalletCreated(address)": TypedContractEvent<
      WalletCreatedEvent.InputTuple,
      WalletCreatedEvent.OutputTuple,
      WalletCreatedEvent.OutputObject
    >;
    WalletCreated: TypedContractEvent<
      WalletCreatedEvent.InputTuple,
      WalletCreatedEvent.OutputTuple,
      WalletCreatedEvent.OutputObject
    >;
  };
}
