/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface SmartAccountFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "createWallet"
      | "entryPoint"
      | "getAddress"
      | "walletImplementation"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "WalletDeployed"): EventFragment;

  encodeFunctionData(
    functionFragment: "createWallet",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "entryPoint",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAddress",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "walletImplementation",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "createWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "entryPoint", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getAddress", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "walletImplementation",
    data: BytesLike
  ): Result;
}

export namespace WalletDeployedEvent {
  export type InputTuple = [wallet: AddressLike, owner: AddressLike];
  export type OutputTuple = [wallet: string, owner: string];
  export interface OutputObject {
    wallet: string;
    owner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SmartAccountFactory extends BaseContract {
  connect(runner?: ContractRunner | null): SmartAccountFactory;
  waitForDeployment(): Promise<this>;

  interface: SmartAccountFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createWallet: TypedContractMethod<
    [owner: AddressLike, salt: BigNumberish],
    [string],
    "nonpayable"
  >;

  entryPoint: TypedContractMethod<[], [string], "view">;

  getAddress: TypedContractMethod<
    [owner: AddressLike, salt: BigNumberish],
    [string],
    "view"
  >;

  walletImplementation: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createWallet"
  ): TypedContractMethod<
    [owner: AddressLike, salt: BigNumberish],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "entryPoint"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getAddress"
  ): TypedContractMethod<
    [owner: AddressLike, salt: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "walletImplementation"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "WalletDeployed"
  ): TypedContractEvent<
    WalletDeployedEvent.InputTuple,
    WalletDeployedEvent.OutputTuple,
    WalletDeployedEvent.OutputObject
  >;

  filters: {
    "WalletDeployed(address,address)": TypedContractEvent<
      WalletDeployedEvent.InputTuple,
      WalletDeployedEvent.OutputTuple,
      WalletDeployedEvent.OutputObject
    >;
    WalletDeployed: TypedContractEvent<
      WalletDeployedEvent.InputTuple,
      WalletDeployedEvent.OutputTuple,
      WalletDeployedEvent.OutputObject
    >;
  };
}
