/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IEntryPoint,
  IEntryPointInterface,
} from "../../../contracts/UserWallet.sol/IEntryPoint";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "sender",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "userOp",
        type: "bytes",
      },
    ],
    name: "executeUserOp",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "sender",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "userOp",
        type: "bytes",
      },
    ],
    name: "validateUserOp",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IEntryPoint__factory {
  static readonly abi = _abi;
  static createInterface(): IEntryPointInterface {
    return new Interface(_abi) as IEntryPointInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IEntryPoint {
    return new Contract(address, _abi, runner) as unknown as IEntryPoint;
  }
}
